---
- name: Fail if not Debian Buster
  fail:
    msg: Currently only Debian Buster is supported
  when: not ansible_distribution == 'Debian' or not ansible_distribution_release == 'buster'

- name: Fail if eula is not accepted
  fail:
    msg: Eula is not accepted, check out https://account.mojang.com/documents/minecraft_eula
  when: minecraft_papermc_eula is undefined or ( not minecraft_papermc_eula | bool )

- name: Install dependencies
  apt:
    name: default-jre-headless
    state: present
    cache_valid_time: '3600'

- name: Set up user
  include_tasks: user.yml

- name: Ensure minecraft and mcrcon directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ minecraft_papermc_user }}'
    group: '{{ minecraft_papermc_group }}'
    mode: '0755'
  loop:
    - '{{ minecraft_papermc_user_home }}/bin'
    - '{{ minecraft_papermc_user_home }}/mcrcon'

- name: Install server
  include_tasks: install.yml

- name: Configure server
  include_tasks: configure.yml

- name: Copy service file
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    group: root
    owner: root
    mode: '0644'
  notify:
    - reload-systemd
    - restart-enable-minecraft
