---
- name: reload-systemd
  systemd:
    daemon_reload: yes

- name: enable-minecraft
  systemd:
    state: enabled
    name: minecraft

- name: restart-minecraft
  systemd:
    state: restarted
    name: minecraft
